language: c

dist: trusty
sudo: required

# Install required distro packages
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install cmake debhelper libgee-0.8-dev libgranite-dev libgtk-3-dev valac libunity-dev libnotify-dev libxml2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libclutter-gtk-1.0-dev libclutter-1.0-dev libclutter-gst-3.0-dev libsqlite3-dev libsoup2.4-dev libwebkit2gtk-4.0-dev

# Build Vocal.
script: mkdir build && cd build && cmake ../ && make